# PyTorch Basic Tensor Operations

This notebook is a quick hands-on guide to core tensor operations used in deep learning.

What you will learn:
1. How `unsqueeze` adds dimensions.
2. How dimension-based reductions work, especially `sum(-1)`.
3. The difference between `reshape` and `view`.
4. How `squeeze` and `unsqueeze` help align tensor shapes.

Recommended reading order: run cells from top to bottom and compare each printed tensor shape.

In [ ]:
import torch

In [ ]:
# 1D tensor and unsqueeze examples
x = torch.tensor([1, 3, 2])
print("x:", x, " shape:", x.shape)

b = x.unsqueeze(-1)
print("unsqueeze(-1):\n", b, " shape:", b.shape)

b = x.unsqueeze(0)
print("unsqueeze(0):\n", b, " shape:", b.shape)

tensor([1, 3, 2]) torch.Size([3])
tensor([[1],
        [3],
        [2]]) torch.Size([3, 1])


## Dimension Reduction Operations

For tensor shape intuition, these are very useful:

1. `sum(dim=...)` and `sum(-1)` (last dimension)
2. `mean(dim=...)`
3. `max(dim=...)` (returns both values and indices)
4. `keepdim=True` to preserve reduced axes as size `1`

`dim=-1` is especially common in deep learning because it targets the last axis regardless of batch dimensions.

In [12]:
# 2D example: rows x cols = (2 x 3)
x2 = torch.tensor([[1, 3, 2],
                   [4, 0, 5]], dtype=torch.float32)
print("x2:\n", x2)
print("shape:", x2.shape)

print("=" * 20)
# Reduce last dimension (same as dim=1 for this 2D tensor)
print("sum(-1):", x2.sum(-1), " shape:", x2.sum(-1).shape)
print("sum(dim=1):", x2.sum(dim=1), " shape:", x2.sum(dim=1).shape)

print("=" * 20)
# Reduce first dimension
print("sum(dim=0):", x2.sum(dim=0), " shape:", x2.sum(dim=0).shape)

print("=" * 20)
# keepdim keeps reduced axis with size 1
print("sum(-1, keepdim=True):\n", x2.sum(-1, keepdim=True),
      " shape:", x2.sum(-1, keepdim=True).shape)

print("=" * 20)
# Other common reductions
print("mean(-1):", x2.mean(-1), " shape:", x2.mean(-1).shape)
max_vals, max_idx = x2.max(dim=-1)
print("max(-1) values:", max_vals, " indices:", max_idx)

x2:
 tensor([[1., 3., 2.],
        [4., 0., 5.]])
shape: torch.Size([2, 3])
sum(-1): tensor([6., 9.])  shape: torch.Size([2])
sum(dim=1): tensor([6., 9.])  shape: torch.Size([2])
sum(dim=0): tensor([5., 3., 7.])  shape: torch.Size([3])
sum(-1, keepdim=True):
 tensor([[6.],
        [9.]])  shape: torch.Size([2, 1])
mean(-1): tensor([2., 3.])  shape: torch.Size([2])
max(-1) values: tensor([3., 5.])  indices: tensor([1, 2])


### Shape-changing operations: reshape, view, squeeze, unsqueeze

These are core operations for preparing tensors in models.

- `reshape(...)`: returns a tensor with new shape (may copy if needed)
- `view(...)`: returns a reshaped **view** when memory is contiguous
- `squeeze(dim)`: removes axes of size 1
- `unsqueeze(dim)`: inserts a size-1 axis

In [13]:
# reshape / view / squeeze / unsqueeze examples
x = torch.arange(12)
print("x:", x)
print("x shape:", x.shape)

print("=" * 20)
# reshape: general purpose
r = x.reshape(3, 4)
print("reshape(3,4):\n", r)
print("shape:", r.shape)

print("=" * 20)
# view: requires contiguous memory
v = x.view(3, 4)
print("view(3,4):\n", v)
print("shape:", v.shape)

print("=" * 20)
# Non-contiguous example: transpose breaks contiguity for view
t = r.t()  # shape (4, 3)
print("transposed shape:", t.shape, " contiguous:", t.is_contiguous())

try:
    t.view(12)
except RuntimeError as e:
    print("view on non-contiguous tensor failed:", e)

# reshape can still work (it may create a copy)
t_flat = t.reshape(12)
print("reshape on non-contiguous tensor works, shape:", t_flat.shape)

print("=" * 20)
# unsqueeze adds a size-1 dimension
u0 = x.unsqueeze(0)
u1 = x.unsqueeze(1)
print("unsqueeze(0) shape:", u0.shape)  # [1, 12]
print("unsqueeze(1) shape:", u1.shape)  # [12, 1]

print("=" * 20)
# squeeze removes size-1 dimensions
y = torch.randn(1, 12, 1)
print("y shape:", y.shape)
print("squeeze() shape:", y.squeeze().shape)      # [12]
print("squeeze(0) shape:", y.squeeze(0).shape)    # [12, 1]
print("squeeze(-1) shape:", y.squeeze(-1).shape)  # [1, 12]

x: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
x shape: torch.Size([12])
reshape(3,4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
shape: torch.Size([3, 4])
view(3,4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
shape: torch.Size([3, 4])
transposed shape: torch.Size([4, 3])  contiguous: False
view on non-contiguous tensor failed: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
reshape on non-contiguous tensor works, shape: torch.Size([12])
unsqueeze(0) shape: torch.Size([1, 12])
unsqueeze(1) shape: torch.Size([12, 1])
y shape: torch.Size([1, 12, 1])
squeeze() shape: torch.Size([12])
squeeze(0) shape: torch.Size([12, 1])
squeeze(-1) shape: torch.Size([1, 12])
